import 'dart:async';
import 'package:flutter/material.dart';
import '../models/course.dart';
import '../services/firestore_service.dart';
import '../services/service_locator.dart';

class CoursesController extends ChangeNotifier {
  final FirestoreService _firestoreService;
  StreamSubscription<List<Course>>? _coursesSubscription;

  List<Course> _courses = [];
  bool _isLoading = true;
  String? _errorMessage;

  CoursesController({FirestoreService? firestoreService})
      : _firestoreService = firestoreService ?? getIt<FirestoreService>() {
    _initStream();
  }

  List<Course> get courses => List.unmodifiable(_courses);
  bool get isLoading => _isLoading;
  String? get errorMessage => _errorMessage;

  void _initStream() {
    _coursesSubscription?.cancel();
    _isLoading = true;
    _errorMessage = null;

    _coursesSubscription = _firestoreService.streamCourses().listen(
      (courseList) {
        _courses = courseList;
        _isLoading = false;
        _errorMessage = null;
        notifyListeners();
      },
      onError: (error) {
        debugPrint('Error streaming courses from Firebase: $error');
        _isLoading = false;
        _errorMessage = error.toString();
        notifyListeners();
      },
    );
  }

  Future<void> addCourse({
    required String title,
    required String description,
    DateTime? deadline,
    String status = 'active',
  }) async {
    final now = DateTime.now();
    final newCourse = Course(
      id: '', // Generated by Firestore
      title: title,
      description: description,
      status: status,
      deadline: deadline,
      createdAt: now,
      updatedAt: now,
    );

    try {
      await _firestoreService.addCourse(newCourse);
    } catch (e) {
      debugPrint('Error adding course to Firebase: $e');
      rethrow;
    }
  }

  @override
  void dispose() {
    _coursesSubscription?.cancel();
    super.dispose();
  }
}
