name: expenses_module
description: Expenses and budget tracking module
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  cloud_firestore: ^5.0.0
  get_it: ^8.0.0
  google_fonts: ^8.0.2
  core_ui:
    path: ../core_ui
  core_services:
    path: ../core_services
